### ISSUE TITLE
Class Conversion returns two times the same values

### ISSUE THREAD

**Issue by jlelse** [afollestad/bridge#10]
I use this class conversion feature.

Although the URL and response content is different, the method ".asClass(...)" returns the same objects with the same values.

**Comment by afollestad** [comment]
That shouldn't be possible, I've tested it pretty heavily. 

Do you have an example?

**Comment by afollestad** [comment]
That's very weird, I'm able to reproduce it. Looking into it.

**Comment by afollestad** [comment]
Fixed

**Comment by afollestad** [comment]
https://github.com/afollestad/bridge/releases/tag/3.1.1

**Comment by jlelse** [comment]
Thanks man!
