### ISSUE TITLE
Conversions as Standalone feature

### ISSUE THREAD

**Issue by jlelse** [afollestad/bridge#11]
Conversion works great!
Is it possible to provide it as standalone feature without doing requests?

**Comment by afollestad** [comment]
I might actually make this a completely separate library, I do agree that it's very useful outside of Bridge :)

**Comment by jlelse** [comment]
Update to this: It would be pretty much what Gson does. But Gson is actually a bit hard to use on Kotlin and also has MANY methods (65k limit!!), so it would be still very usefull, if there would be a smart alternative.

**Comment by envoy47** [comment]
Please some body tell me how to use brige with recyclerview.

**Comment by afollestad** [comment]
@envoy47 Bridge is not a UI library.

**Comment by afollestad** [comment]
https://github.com/afollestad/ason
