### ISSUE TITLE
 Typo in the example about JSON Response Conversion.

### ISSUE THREAD

**Issue by Ahmed-Emad** [afollestad/bridge#15]
There is a typo in the example about JSON Response Conversion.
The name property in the json response is 'name' not 'full_name'.

```java
@Body(name = "full_name")
public String name;
```

```json
{
    "name": "Aidan Follestad",
    ...
}
```

**Comment by afollestad** [comment]
That's what pull requests are for 😉

On Fri, May 27, 2016, 5:26 PM Ahmed Emad Barakat <notifications@github.com>
wrote:

> There is a typo in the example about JSON Response Conversion.
> The name property in the json response is 'name' not 'full_name'.
>
> @Body(name = "full_name")public String name;
>
> {
>     "name": "Aidan Follestad",
>     ...
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/afollestad/bridge/issues/15>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABvGBdX0Yx2AtfeMmUSMSJ9w2sLHtl52ks5qF2-XgaJpZM4Io6Om>
> .
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662
