### ISSUE TITLE
Duplicate Avoidance does not account for body

### ISSUE THREAD

**Issue by rubengees** [afollestad/bridge#18]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.

- Library version: `3.2.4` (`3.2.5` not working for me somehow)
- Device OS version: `6.0.1`
- Device Manufacturer: `OnePlus`
- Device Name: `3`
 
###### Reproduction Steps

Do two or more Requests with everything the same except the body:

```java
Bridge.post("https://example.com").body(new Form().add("parameter1", "value1"))
      .request(new Callback() {
    @Override
    public void response(@NonNull Request request, @Nullable Response response,
                         @Nullable BridgeException e) {
        //As expected
    }
});

Bridge.post("https://example.com").body(new Form().add("parameter2", "value2"))
      .request(new Callback() {
    @Override
    public void response(@NonNull Request request, @Nullable Response response,
                         @Nullable BridgeException e) {
        //Same as above, even though something different is expected
    }
});
```

###### Expected Result

Different results for both callbacks, based on the body.

###### Actual Result

Same results for both callbacks.

###### Thoughts

I haven't looked at the code and I am not sure if it would be easy to add this. If not, an option for turning duplicate avoidance off would be great.

Thanks in advance!

**Comment by afollestad** [comment]
That's a good idea for enhancement!

I'll include that in the next release.

**Comment by rubengees** [comment]
Great! :+1:

**Comment by afollestad** [comment]
Finally in the latest release.

It uses MD5 hashes on bodies for duplicate avoidance. It's automatic everywhere *except* the `TransferPipe` (`Pipe.forStream()`) where you have to provide an ID, since reading the entire stream to generate a hash is impractical and inefficient.
