### ISSUE TITLE
Retry on failure, new authorization header

### ISSUE THREAD

**Issue by ritdaw** [afollestad/bridge#27]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

I am using Bridge in one of my apps and on occasion we have to request a new oauth token for authentication. We do this by listening out for 401 response codes, then request a new token.

In OkHttp it's possible to retry requests when a 401 response is received by passing in a new authorization header.

https://github.com/square/okhttp/wiki/Recipes
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Authenticate.java

Bridge is far superior in response conversion and want to keep using it :) Any thoughts on the best way of handling whilst continuing to use bridge?

**Comment by afollestad** [comment]
https://github.com/afollestad/bridge/releases/tag/4.1.0

Added retry support, with an optional callback that you can use to modify requests before they are sent. I also added built-in Basic Auth support.

**Comment by ritdaw** [comment]
That is awesome, thanks for adding so quickly!

**Comment by afollestad** [comment]
No problem! Let me know if you have any more issues

**Comment by ritdaw** [comment]
Has been working perfectly. Nice little addition to the library.
