### ISSUE TITLE
Response is not passed to the request after Validator returns false

### ISSUE THREAD

**Issue by RubenGees** [afollestad/bridge#3]
As the title states I have a top-level validator which tests each response against an error code. If it fails I want to read a message from the response and display it, but the response is not passed back to the callback.

My Code:

```
Bridge.client().config().validators(new ResponseValidator() {
            @Override
            public boolean validate(@NonNull Response response) throws Exception {
                return response.asJsonObject().getInt("error") == 0;
            }

            @NonNull
            @Override
            public String id() {
                return "default-validator";
            }
        });
```

My Request:

```
 Bridge.client().get("someURL").request(new Callback() {
            @Override
            public void response(Request request, Response response, BridgeException e) {
                if(e == null){
                   //Do something
                }else{
                    switch(e.reason()){
                        case BridgeException.REASON_RESPONSE_VALIDATOR_FALSE:
                            try {
                                Toast.makeText(getActivity(), "A problem occured:" + " " + response.asJsonObject().getString("msg"), Toast.LENGTH_LONG).show(); //Nullpointer here
                            } catch (JSONException | BridgeException e1) {
                                Toast.makeText(getActivity(), "A problem occured. Please try again.", Toast.LENGTH_LONG).show();
                            }
                            break;
                    }
                 }

            }
        });
```

Something wrong with my ocde or an  library-issue?

**Comment by afollestad** [comment]
That means your validator method returned false. Return true to indicate success.

**Comment by RubenGees** [comment]
Yes, sure. I return false if the JSONObject I receive has a field error with 1. (All responses I get from my server have that in common) Isn't that what the Validator is for? If it fails (For example: Wrong Password) and the validator returns false I want to show the user why it failed and that info is in the field msg, which I can't access because the Response is not passed back.

**Comment by afollestad** [comment]
You can throw an Exception within the validator method and the message will be passed to your response.

**Comment by RubenGees** [comment]
Ahh yes thank you, didn't think of that.
I don't want to annoy you, but why did you make the design decision to not pass back the response, if the validator returned false? I think there are some use-cases (like mine) where it would be helpful.

**Comment by afollestad** [comment]
You can still get the response from the `BridgeException` you get when the response is invalid or unsuccessful. You can get the Request too.

```java
BridgeException e = // ...
if (e.reason() == BridgeException.REASON_RESPONSE_VALIDATOR_FALSE) {
        // Validator returned false, REASON_RESPONSE_VALIDATOR_ERROR
        // can be used for throwing an Exception inside the validator.
        String validatorId = e.validatorId();
        Response response = e.response();
        Request request = e.request();
}
```

**Comment by RubenGees** [comment]
Okay, thank you! Is this documented in the README? If not, maybe add it? :)

**Comment by afollestad** [comment]
It is: https://github.com/afollestad/bridge#error-handling

**Comment by afollestad** [comment]
And https://github.com/afollestad/bridge#validators

**Comment by RubenGees** [comment]
Okay, thank you again. I should read everything :D
