### ISSUE TITLE
Jitpack dependency not working

### ISSUE THREAD

**Issue by wasdennnoch** [afollestad/bridge#5]
I've tried different versions, nothing seems to work.

Also, jitpack.io gives me the url "com.github.afollestad:bridge:1.6.2", but the README says "com.afollestad:bridge:1.6.2". I've tried both, no result.

**Comment by afollestad** [comment]
com.afollestad is a custom domain version of com.github.afollestad. They both lead to the same result.

Did you include the repository?

**Comment by afollestad** [comment]
```Gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.afollestad:bridge:1.6.2'
}
```

**Comment by wasdennnoch** [comment]
Interesting, I had to put the jitpack dependency in the application-level gradle file. The "normal" maven plugin worked in the top-level gradle file. Alright, now it's working.
