### ISSUE TITLE
Possible redirection issues

### ISSUE THREAD

**Issue by wasdennnoch** [afollestad/bridge#6]
Title says everything. When supplying an https url to .get, .post etc response.asString() returns null. Tested with domain https://puush.me

**Comment by afollestad** [comment]
Unfortunately I'm unable to reproduce this.

It works fine with HTTPS URLs I've tested with.

**Comment by wasdennnoch** [comment]
Okay, I tested a bit and found out that https wasn't the problem but a redirection that causes the return of null. 

https://puush.me/login/go?k=[API key from shared prefs] redirects (302) to http://puush.me/account/ which permantly (301) redirects to https://puush.me/account

When I change lhe login url to http it works for whatever reason.

**Comment by afollestad** [comment]
@wasdennnoch I think Java might avoid that redirection on purpose.

http://stackoverflow.com/a/1884427

**Comment by afollestad** [comment]
Officially fixed in the latest commits.

Redirection is followed by default, it can be opted out of from the config. `Response` also has a `didRedirect()` method that indicates of redirection was followed to get a response or not.
